language: generic
sudo: required

services:
  - docker

before_install: 
  - docker build -t ottter/docker-react -f Dockerfile.dev .

script:
  - docker run -r CI=true ottter/docker-react npm run test