version: '3'
services: 
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev  
    ports:
      - "3000:3000"
    volumes:
      - /home/james/udemy/app/node_modules
      - .:/home/james/udemy/app        
  tests:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/james/udemy/app/node_modules
      - .:/home/james/udemy/app
    command: ["npm", "run", "test"]